var EMPTY_STRING = "";
var ONE_CHAR_STRING = " ";
var LEFT_DELIMITER = '{{';
var RIGHT_DELIMITER = '}}';
var ATTR_PREFIX = "vo-";
var MODEL_ATTR = ATTR_PREFIX + "model";
var EVENT_ATTR_PREFIX = ATTR_PREFIX + "on:";

module.exports = {
    EMPTY_STRING: EMPTY_STRING,
    ONE_CHAR_STRING: ONE_CHAR_STRING,
    LEFT_DELIMITER: LEFT_DELIMITER,
    RIGHT_DELIMITER: RIGHT_DELIMITER,
    ATTR_PREFIX: ATTR_PREFIX,
    EVENT_ATTR_PREFIX: EVENT_ATTR_PREFIX,
    MODEL_ATTR: MODEL_ATTR
};